### ISSUE TITLE
Using Mocha for Testing. Is there a trick ?

### ISSUE THREAD

**Issue by OmarOufDev** [young-steveo/bottlejs#107]
I am trying to integrate bottlejs into a project.
the project runs fine if i run it "node test.js" . 
```
// test.js
import { IRespawnListLogic } from "./Services/_Services.index";
import { bottle } from "./BaseLayer/BottleManager";

const resplistlog = bottle.container.RespawnListLogic;
const opt = bottle.container.OptionsVerification;
console.log(new opt({enabled: "true"}).validate());

console.log(resplistlog.addEntry("1", "1"));
console.log(resplistlog.addOptionsToEntry("1",{enabled: true}));
```

however if i use a test via mocha. "mocha Tests" . it throws a type error. 
```
        const validatedOptions = new this.optionsVerification(options).validate();
                                 ^

TypeError: this.optionsVerification is not a constructor
    at RespawnListLogic.addOptionsToEntry (E:\TypescriptTutorial\RespawnList\Services\RespawnListLogic.js:84:34)
    at Suite.describe (E:\TypescriptTutorial\RespawnList\Tests\RespawnListTest.js:55:18)
    at Object.create (C:\Users\omaro\AppData\Roaming\npm\node_modules\mocha\lib\interfaces\common.js:112:19)
    at context.describe.context.context (C:\Users\omaro\AppData\Roaming\npm\node_modules\mocha\lib\interfaces\bdd.js:44:27)
    at Suite.describe (E:\TypescriptTutorial\RespawnList\Tests\RespawnListTest.js:52:5)
    at Object.create (C:\Users\omaro\AppData\Roaming\npm\node_modules\mocha\lib\interfaces\common.js:112:19)
    at context.describe.context.context (C:\Users\omaro\AppData\Roaming\npm\node_modules\mocha\lib\interfaces\bdd.js:44:27)
    at Object.<anonymous> (E:\TypescriptTutorial\RespawnList\Tests\RespawnListTest.js:7:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at C:\Users\omaro\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\Users\omaro\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:228:14)
    at Mocha.run (C:\Users\omaro\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:536:10)
    at Object.<anonymous> (C:\Users\omaro\AppData\Roaming\npm\node_modules\mocha\bin\_mocha:582:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

heres how i use bottle to save the class.
```
bottle.factory("OptionsVerification", () => OptionsVerification);
```

heres how i inject it into the class.
```
   private optionsVerification = bottle.container.OptionsVerification;
```
heres how i call it. 
```
        const validatedOptions = new this.optionsVerification(options).validate();
```

Here's the repo url.
https://github.com/OmarOufDev/RespawnList/tree/bottle

**Comment by young-steveo** [comment]
As far as I can tell looking at the code, everything should have worked.  My only comment is that you're using bottle as a service locator, and since the system under test loads the BottleManager, there's no good way to mock your `OptionsVerification` object.  Mocking dependencies in tests is half the reason to use an IoC like bottle.

I don't know why `this.optionsVerification is not a constructor ` because you have registered a factory correctly.   Something in the bootstrap process of the mocha flow is not registering something.  IT's hard to tell without actively debugging it.

Maybe if you refactor a bit to use dependency injection (i.e. the constructor should take an interface for OptionsVerification) in your RespawnListLogic class it will become more evident.

**Comment by OmarOufDev** [comment]
i tried to construct the object before returning it. like.
```
bottle.factory("OptionsVerification", () => {
    return {
        get(options: any) {
          return new OptionsVerification(options);
        }
    }
});
```
and i call it like this now.
```
const validatedOptions = this.optionsVerification.get(options).validate();
```
same problem persisted. 
``` 
E:\TypescriptTutorial\RespawnList\BaseLayer\BottleManager.js:19
            return new _Services_index_1.OptionsVerification(options);
                   ^

TypeError: _Services_index_1.OptionsVerification is not a constructor
    at Object.get (E:\TypescriptTutorial\RespawnList\BaseLayer\BottleManager.js:19:20)
    at RespawnListLogic.addOptionsToEntry (E:\TypescriptTutorial\RespawnList\Services\RespawnListLogic.js:84:59)
    at Suite.describe (E:\TypescriptTutorial\RespawnList\Tests\RespawnListTest.js:55:18)
    at Object.create (C:\Users\omaro\AppData\Roaming\npm\node_modules\mocha\lib\interfaces\common.js:112:19)
    at context.describe.context.context (C:\Users\omaro\AppData\Roaming\npm\node_modules\mocha\lib\interfaces\bdd.js:44:27)
    at Suite.describe (E:\TypescriptTutorial\RespawnList\Tests\RespawnListTest.js:52:5)
    at Object.create (C:\Users\omaro\AppData\Roaming\npm\node_modules\mocha\lib\interfaces\common.js:112:19)
    at context.describe.context.context (C:\Users\omaro\AppData\Roaming\npm\node_modules\mocha\lib\interfaces\bdd.js:44:27)
    at Object.<anonymous> (E:\TypescriptTutorial\RespawnList\Tests\RespawnListTest.js:7:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at C:\Users\omaro\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\Users\omaro\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:228:14)
    at Mocha.run (C:\Users\omaro\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:536:10)
    at Object.<anonymous> (C:\Users\omaro\AppData\Roaming\npm\node_modules\mocha\bin\_mocha:582:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
``

**Comment by OmarOufDev** [comment]
also tried this 
```
    /** creates an instance of the class */
    constructor(optionsVerification: any) {
        this.optionsVerification = optionsVerification;
        this.storage = [];
    }

```
```
//bottlemanager.ts
bottle.factory("OptionsVerification", () => OptionsVerification);
bottle.service("RespawnListLogic", RespawnListLogic, "OptionsVerification");
```

```
E:\TypescriptTutorial\RespawnList\Services\RespawnListLogic.js:84
        const validatedOptions = new this.optionsVerification(options).validate();
                                 ^

TypeError: this.optionsVerification is not a constructor
    at RespawnListLogic.addOptionsToEntry (E:\TypescriptTutorial\RespawnList\Services\RespawnListLogic.js:84:34)
    at Suite.describe (E:\TypescriptTutorial\RespawnList\Tests\RespawnListTest.js:55:18)
    at Object.create (C:\Users\omaro\AppData\Roaming\npm\node_modules\mocha\lib\interfaces\common.js:112:19)
    at context.describe.context.context (C:\Users\omaro\AppData\Roaming\npm\node_modules\mocha\lib\interfaces\bdd.js:44:27)
    at Suite.describe (E:\TypescriptTutorial\RespawnList\Tests\RespawnListTest.js:52:5)
    at Object.create (C:\Users\omaro\AppData\Roaming\npm\node_modules\mocha\lib\interfaces\common.js:112:19)
    at context.describe.context.context (C:\Users\omaro\AppData\Roaming\npm\node_modules\mocha\lib\interfaces\bdd.js:44:27)
    at Object.<anonymous> (E:\TypescriptTutorial\RespawnList\Tests\RespawnListTest.js:7:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at C:\Users\omaro\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\Users\omaro\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:228:14)
    at Mocha.run (C:\Users\omaro\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:536:10)
    at Object.<anonymous> (C:\Users\omaro\AppData\Roaming\npm\node_modules\mocha\bin\_mocha:582:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

```

**Comment by young-steveo** [comment]
I cloned your repo to try and run your test suite, but there are other problems preventing me from executing the code.  Mocha will not run dude to some missing configuration.  Your local environment must have something enabled that is not in your package.json.

I can tell that the problem is not with bottle...  Since you are using TypeScript, try typing this argument instead of using `any`: https://github.com/OmarOufDev/RespawnList/blob/constructorInjection/Services/RespawnListLogic.ts#L25

That won't solve your problem but it should help you debug it.
