### ISSUE TITLE
TypeError: Service is not a constructor

### ISSUE THREAD

**Issue by basickarl** [young-steveo/bottlejs#73]
```
'use strict';

import Bottle from 'bottlejs';

import mysql from 'mysql';
import mysqlMock from 'test/mocks/mysql.js';

const TYPES = {
  mysql: 'mysql'
};

const bottle = new Bottle();

if (process.env.NODE_ENV !== 'test') {
  bottle.service(TYPES.mysql, mysql);
} else {
  bottle.service(TYPES.mysql, mysqlMock);
}

console.log('mysql ->', bottle.container.mysql); // <--- di.js:35:25
```

I'm getting: 
```
TypeError: Service is not a constructor
    at GenericProvider.GenericFactory [as $get] (/home/karlm/dev/node/frontdoor/node_modules/bottlejs/dist/bottle.js:451:20)
    at Object.getService [as mysql] (/home/karlm/dev/node/frontdoor/node_modules/bottlejs/dist/bottle.js:368:89)
at Object.<anonymous> (/home/karlm/dev/node/frontdoor/src/utils/di.js:35:25)
```

I realize that "mysql" is not a function but rather an object. Why can't I return this?

**Comment by basickarl** [comment]
Used a factory to fix it!

```
bottle.factory(TYPES.mysql, () => mysql);
```

**Comment by young-steveo** [comment]
@basickarl Yes, `bottle.service` requires a constructor. Your factory solution is how I would handle it.
