### ISSUE TITLE
Getting service fails after calling resetProviders

### ISSUE THREAD

**Issue by tvjg** [young-steveo/bottlejs#87]
Calling `bottle#resetProviders` causes subsequent calls to retrieve a service from the container fail. This can be demonstrated with a short example.

```javascript
var context = require('bottlejs').pop('context')

context.service('A', function A () {}, 'B')
context.service('B', function B () {})

context.container.A

context.resetProviders()

context.container.A
```

This yields the following stack trace.

    TypeError: fullname.split is not a function
        at Object.getNestedService (/Users/jguidry/Code/iz/api/querulous.js/node_modules/bottlejs/dist/bottle.js:61:25)
        at Array.map (native)
        at GenericProvider.GenericFactory [as $get] (/Users/jguidry/Code/iz/api/querulous.js/node_modules/bottlejs/dist/bottle.js:490:29)
        at Object.getService [as A] (/Users/jguidry/Code/iz/api/querulous.js/node_modules/bottlejs/dist/bottle.js:372:39)
        at repl:1:18
        at sigintHandlersWrap (vm.js:22:35)
        at sigintHandlersWrap (vm.js:73:12)
        at ContextifyScript.Script.runInThisContext (vm.js:21:12)
        at REPLServer.defaultEval (repl.js:346:29)
        at bound (domain.js:280:14)

From what I can tell, this is because GenericFactory mutates the copy of deps stored in the closure. Guessing [this code](https://github.com/young-steveo/bottlejs/blob/master/src/Bottle/service.js#L13) predates `resetProviders` and was written with the presumption it would only ever be called once. I will open a pull request with a potential fix for you to review. Thanks in advance and nice work on this project!

**Comment by young-steveo** [comment]
Thanks for the PR!  fix available now in [v1.6.1](https://github.com/young-steveo/bottlejs/releases/tag/v1.6.1)
